### ISSUE TITLE
Class OAuth not found

### ISSUE THREAD

**Issue by cr0co** [Surfoo/geocaching-api#4]
Hello

im getting error;
PHP Fatal error:  Class 'Geocaching\OAuth\OAuth' not found in index.php on line 38

any fixes ?

Greetings

**Comment by Surfoo** [comment]
Hello,

How did you installed the library?

**Comment by cr0co** [comment]
i uploaded all files and put 
{
    "require": {
        "geocaching/api": "1.2"
    }
}
into the json file.

**Comment by Surfoo** [comment]
ok, but did you install and run Composer?

**Comment by cr0co** [comment]
how to ? 
can you help me with this? :)

**Comment by Surfoo** [comment]
Did you follow the link in the README.md?
Please read https://getcomposer.org/doc/00-intro.md#system-requirements and try :)
