### ISSUE TITLE
Site not working

### ISSUE THREAD

**Issue by wolojoli** [Surfoo/geocaching-api#5]
The demo site isn't working anymore.

**Comment by Surfoo** [comment]
What's wrong with the demo? I just tested it, and it works for me.

**Comment by wolojoli** [comment]
Tested it with the Staging site (and key/secret) and got this error:
oauth_error_message=token%20parameter%20cannot%20be%20null%20or%20empty

The Live site seems to be working

**Comment by wolojoli** [comment]
Seems that the staging site isn't available at all, so the error is on GC-side,
